# Generated by Django 4.1.5 on 2023-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_video", models.CharField(max_length=2000)),
                ("output", models.CharField(max_length=200000)),
            ],
        ),
        migrations.DeleteModel(name="Student",),
    ]
